config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'schedules#index'
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :text, presence: true
  belongs_to :user

  validates :text, :title, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :schedules
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )

    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: [:update, :destroy, :edit]
  before_action :move_to_index, except: [:index]
 
  def index
    @schedules = Schedule.includes(:user).order("created_at DESC")
  end

  def new
    @schedule = Schedule.new
  end

  def create
    Schedule.create(schedule_params)
  end

  def destroy
    schedule = Schedule.find(params[:id])
    schedule.destroy
  end

  def edit
  end

  def update
    schedule = Schedule.find(params[:id])
    schedule.update(schedule_params)
  end

  private
  def schedule_params
    params.require(:schedule).permit(:title, :text, :memo).merge(user_id: current_user.id)
  end
  
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end 
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    authorization
  end

  private
  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authorization
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body text="white">
    <div class="full-page">
      <%= yield %>
    </div>  
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: @schedule, local: true) do |form| %>
      <%= render 'layouts/error_messages', model: form.object %>
      <%= form.date_field :title, class: "date" %>
      <%= form.text_field :text, placeholder: "予定名", class: "schedule_name" %>
      <%= form.text_field :memo, placeholder: "備考", class: "schedule_detail" %>
      <%= form.submit "作成", class: "edit_complete" %>
    <% end %>

app/views/schedules/_schedule.html.erb
<div class="content_parts">
  <% if user_signed_in? && current_user.id == schedule.user_id %>
    <span class="title">
      <p><%= schedule.title %></p>
    </span>
    <span class="text">
      <%= link_to schedule.text, edit_schedule_path(schedule.id), method: :get %>
    </span>
    <div class="delete_contents">
      <%= link_to '削除', schedule_path(schedule.id), method: :delete, class: "delete" %>
    </div>
  <% end %>
</div>

app/views/schedules/create.html.erb
<div class="finish contents">
  <div class="complete">
    <%= link_to '作成が完了しました', root_path %>
  </div>
</div>

app/views/schedules/destroy.html.erb
<div class="main contents">
  <div class="complete">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">予定一覧に戻る</a>
  </div>
</div>

app/views/schedules/edit.html.erb
<div class="main contents">
  <div class="edit_contents">
    <%= link_to '戻る', root_path, class: "root"%>
    <h4>編集する</h4>
    <div class="edit_forms">
      <%= render partial: "form", locals: { schedule: @schedule } %>
    </div>
  </div>
</div>

app/views/schedules/index.html.erb
<header>
  <%= render "shared/header" %>
</header>
<div class="main_contents">
  <% @schedules.each do |schedule| %>
    <%= render partial: "schedule", locals: { schedule: schedule } %>
  <% end %>
</div>

app/views/schedules/new.html.erb
<div class="main contents">
  <div class="post_new">
    <%= link_to '戻る', root_path, class: "root"%>
    <h3>作成する</h3>
    <%= render partial: "form", locals: { schedule: @schedule } %>
  </div>
</div>

app/views/schedules/update.html.erb
<div class="main contents">
  <div class="complete">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">予定一覧に戻る</a>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="header">
      <div class="top_bar">
        <h1 class="grid-6"><p style="text-align:center"><a href="/">Planner</a></p></h1>
        <% if user_signed_in? %>
          <div class="user_bar grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "user_delete" %>
            <%= link_to "予定作成", new_schedule_path, class: "create" %>
          </div>
          <% else %>
          <div class="user_bar grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>